---
title: "BA exploratory analysis"
author: "Matilde Jacobsen"
date: "created: 10/14/2020, last updated: `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---
#Setup
```{r setup, include=FALSE}
#Clean environment
rm(list = ls())
#Load packages
pacman::p_load(readr,dplyr,lme4,lmerTest,mgcv,tidyverse, scales)

#Load data
data <- read_csv("data.csv")
```

#Preproces
```{r}
#Making RHAD2
#Binary hues
purple <- 250.6
orange <- 46.1
chartreuse <- 80.9
cyan <- 165.2
#Hues of each seed color 
dark_rose <- 327.55
mustard <- 49.85
grass_green <- 117.98
ocean_blue <- 179.34
#Hues of each focal color 
red <- 12.2 + 360
yellow <- 62.4
green <- 136.5
blue <- 193.6
#Calculating deltas
#dark rose pairs
dark_rose - purple
red - dark_rose

#mustard pairs
mustard - orange
yellow - mustard

#grass green pairs
grass_green - chartreuse
green - grass_green

#ocean blue pairs
ocean_blue - cyan
blue - ocean_blue

#Creating the alternative hue and RHAD 2
data <- data %>% 
  mutate(Alternative_focal = case_when(
          Color_label_matched == "seed mustard" ~ orange,
          Color_label_matched == "seed grass green" ~ chartreuse,
          Color_label_matched == "seed ocean blue" ~ cyan,
          Color_label_matched == "seed dark rose" ~ purple)) %>% 
  mutate(
    Dif2 = Hue_matched - Alternative_focal,
    RHAD2 = 100/(Seed - Alternative_focal)*Dif2
  )

#Danish only
danish <- data %>% filter(Language == "Danish")

```

#Analysis
```{r}
exp_model <- lmer(
  RHAD2 ~ Generation:Condition + 
  (1 + Generation + Condition + Generation:Condition | Color_label_matched) + 
  (1 + Generation + Condition + Generation:Condition| Chain) +
  (1 + Generation + Condition + Generation:Condition| Chain:Subject), 
  data = danish, 
  REML = T, 
  control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  check.nobs.vs.nRE = "ignore",
  optCtrl = list(
    ftol_abs = 1e-10, 
    xtol_abs = 1e-10,
    maxeval = 10000
  )))

summary(exp_model)

coef(exp_model)

```

#Modeling seeds seperately
```{r}
#Subsets by color
d_red <- danish %>% filter(Color_label_matched == "seed dark rose")
d_yellow <- danish %>% filter(Color_label_matched == "seed mustard")
d_green <- danish %>% filter(Color_label_matched == "seed grass green")
d_blue <- danish %>% filter(Color_label_matched == "seed ocean blue")

#trying with the full model structure
exp_model2 <- lmer(
  RHAD2 ~ Generation + Color_label_matched +
  (1 + Generation + Condition + Generation:Condition| Chain) +
  (1 + Generation + Condition + Generation:Condition| Chain:Subject),
  data = danish, 
  REML = T, 
  control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  check.nobs.vs.nRE = "ignore",
  optCtrl = list(
    ftol_abs = 1e-10, 
    xtol_abs = 1e-10,
    maxeval = 10000
  )))

summary(exp_model2)
##NB: failed to converge

#dark rose
exp_dark_rose <- lm(RHAD2 ~ Generation:Condition, data = d_red)
summary(exp_dark_rose)

#Significantly negative slope (B=-0.8495, p < .001)

#mustard
exp_mustard <- lm(RHAD2 ~ Generation:Condition, data = d_yellow)
summary(exp_mustard)

#Significantly positive slope (B=5.584 , p > 0.01)

#ocean blue
exp_ocean_blue <- lm(RHAD2 ~ Generation:Condition, data = d_blue)
summary(exp_ocean_blue)

#Slightly positive slope, but not significant (B=0.1300, p = 0.7)

#grass green
exp_grass_green <- lm(RHAD2 ~ Generation:Condition, data = d_green)
summary(exp_grass_green)

#Slightly negative slope, but not significant (B=-0.4851, p = 0.2)

```

